#! /bin/sh

sxhkd &

for monitor in $(xrandr | grep '^[[:alnum:]-]\+[[:space:]]\+connected' | cut -d' ' -f1)
do
    bspc monitor $monitor -d I II III IV V VI VII VIII IX X
done

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on # move to desktop 8 and follow (i.e., switch view to 8 as well)
bspc rule -a Conky state=floating center=on rectangle="242x1080+1168+13"
bspc rule -a xpad state=floating
bspc config external_rules_command "$(which bspwm-rules)"

bar&
stalonetray&
compton&
